import turtle
wn = turtle.Screen()
wn.bgcolor("lightgreen")
wn.title("Segitiga")
alex = turtle.Turtle()
alex.color("red")
alex.pensize(3)
alex.forward(50)
alex.right(90)
alex.forward(30)
alex.right(120)
alex.forward(60)
al = turtle.Turtle()
al.color("yellow")
al.pensize(3)
al.forward(50)
al.left(90)
al.forward(30)
al.left(120)
al.forward(60)
d = turtle.Turtle()
d.color("Green")
d.pensize(3)
d.forward(90)
d.left(90)
e = turtle.Turtle()
e.color("White")
e.pensize(3)
e.forward(90)
e.right(90)
g = turtle.Turtle()
g.color("Purple")
g.pensize(3)
g.left(90)
g.forward(90)
g.left(90)
g.forward(90)
g.left(90)
g.forward(90)
g.right(90)
g.forward(90)
g.right(90)
g.forward(180)
g.left(90)
g.forward(90)
f = turtle.Turtle()
f.color("Green")
f.pensize(3)
f.right(90)
f.forward(90)
f.right(90)
f.forward(90)
f.right(90)
f.forward(90)
f.left(90)
f.forward(90)
f.left(90)
f.forward(180)
f.right(90)
f.forward(90)
wn.mainloop
