import turtle
wn = turtle.Screen()
wn.bgcolor("lightgreen")
wn.title("Hello, Tess!")
tess=turtle.Turtle()
tess.color("blue")
tess.pensize(3)
tess.forward(50)
tess.left(120)
tess.forward(30)
tess.left(90)
tess.forward(30)
alex = turtle.Turtle()
alex.color("red")
alex.pensize(3)
alex.forward(60)
alex.right(90)
alex.forward(30)
alex.right(120)
alex.forward(60)
c = turtle.Turtle()
c.color("Purple")
c.pensize(3)
c.left(180)
c.forward(30)
c.left(150)
c.forward(30)
c.right(90)
d = turtle.Turtle()
d.color("Green")
d.pensize(3)
d.forward(90)
d.left(90)
e = turtle.Turtle()
e.color("Yellow")
e.pensize(3)
e.right(90)
e.forward(30)
d = turtle.Turtle()
d.color("White")
d.pensize(3)
d.forward(90)
d.right(90)
wn.mainloop
